/*****
 Auto-generated by goa, do not modify
******/

package main

/* Task handler */

type TaskHandler struct {
	w http.ResponseWriter
	r *http.Request
}

// Implements TaskResource
//
// func (c *TaskHandler) Index(since *time.Time) *TaskCollection { }
// func (c *TaskHandler) Show(id uint) (*Task, *ResourceNotFound) { }
// func (c *TaskHandler) Create(p *TaskDetails) { }
// func (c *TaskHandler) Update(body *TaskDetails, id uint) { }
// func (c *TaskHandler) Delete(id uint) *ResourceNotFound { }
