/*****
 Auto-generated by goa, implement handler actions
******/

package main

import "strconv"

// Index
func (h *TaskHandler) Index() *TaskCollection {
	models := db.LoadAll()
	tasks := make([]Task, len(models))
	for i, m := range models {
		task, _ := RenderTask(&m)
		tasks[i] = *task
	}
	return &TaskCollection{Count: uint(len(tasks)), Items: tasks}
}

// Show
func (h *TaskHandler) Show(id uint) (*Task, *ResourceNotFound) {
	m := db.Load(id)
	if m == nil {
		h.Respond(404)
		return nil, &ResourceNotFound{Id: id, Resource: "tasks"}
	}
	task, _ := RenderTask(m)
	return task, nil
}

// Create
func (h *TaskHandler) Create(p *TaskDetails) {
	id := db.Create(p.Details)
	h.Respond(201).WithLocation("/task/" + strconv.Itoa(int(id)))
}

// Update (upsert semantic)
func (h *TaskHandler) Update(body *TaskDetails, id uint) {
	newId := db.Update(id, body.Details)
	if newId != id {
		h.Respond(201).WithLocation("/tasks/" + strconv.Itoa(int(newId)))
	} else {
		h.Respond(204)
	}
}

// Delete
func (h *TaskHandler) Delete(id uint) *ResourceNotFound {
	if db.Delete(id) == 0 {
		h.Respond(404)
		return &ResourceNotFound{Id: id, Resource: "tasks"}
	}
	c.Respond(204)
	return nil
}
